# Generated by Django 4.0.6 on 2022-07-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('occasion', models.CharField(max_length=50)),
                ('date_and_time', models.DateTimeField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'reservation_form',
            },
        ),
    ]
