# Generated by Django 4.0.6 on 2022-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrus', '0002_alter_reservation_form_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_form',
            name='occasion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
