# Generated by Django 4.0.6 on 2022-07-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrus', '0003_alter_reservation_form_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_form',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
